# Generated by Django 3.2.5 on 2021-08-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMCE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
