# Generated by Django 3.2.5 on 2021-08-17 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AMCE', '0002_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='equipo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AMCE.equipo'),
        ),
    ]
