# Generated by Django 3.2.5 on 2021-08-17 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMCE', '0003_profile_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='equipo',
        ),
    ]
