# Generated by Django 3.2.5 on 2021-08-18 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AMCE', '0005_profile_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMCE.equipo'),
        ),
    ]
