# Generated by Django 3.2.5 on 2021-08-18 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AMCE', '0008_alter_profile_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='equipo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AMCE.equipo'),
        ),
    ]
