# Generated by Django 3.2.5 on 2021-08-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMCE', '0009_alter_profile_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='equipo',
        ),
    ]
